### ISSUE TITLE
Some issues in PvP that might be connected with the spell delay implemented.

### ISSUE THREAD

**Issue by neroz7** [ccshiro/cc-buglist#172]
After testing PvP in arena with two of my friends, here's some of the issues we found present in the game, the first one being what I think is a camera problem, causing characters to do 180º degrees spin for no reason, making casters miss their cast because of LoS and such, the other issue is a harder to prove one, but I'm pretty sure it's happening and it's specially noticable in arena. I started experiencing some delays with my kick, I know kick is supposed to share GCD with other rogue abilitys in vanilla, but this was weird, I would kick spells, and a small delay would be felt, as if enemy was hit by the ability but since it was too close to the casting to end he would have casted the spell anyways without the kick having worked, I experienced this multiple times, same for my friend with counterspell when he was playing mage, I found it more noticable in the arena for some reason, but we could still replicate this in duels outside. Shiv also has a slight problem, but this one might be, I think the poison application of the spell is coming in too late after the spell is executed. you can feel a delay, maybe I'm wrong but these are some of the issues I found while testing Arena on corecraft. 

Another thing unrelated to mechanics and spells, you can make a 2v2 team, get 3 people into it, queue 2v2 and join in with 3 people, playing 2v2 with 3 people in your team :^).

**Comment by Bugreporta** [comment]
Spell Lock has a slight delay aswell.

**Comment by Iliana-sc** [comment]
turning around is a duplicate of #62
delay is a duplicate of #162 and is not a bug
the queue pvp queue issue is a duplicate of #98

**Comment by neroz7** [comment]
I can tell you 100% this delay I'm talking about is not working like in retail.

**Comment by Iliana-sc** [comment]
and I can tell you 100% that you're wrong, look at any pvp video frame by frame

**Comment by neroz7** [comment]
I'm not sure you understand what delay I'm refering to, it's not the spell delay, it's that sometimes the spell goes off and it's effect is either not felt or only felt in a delay. Example : Shiv goes in, dmg is applied, poison is applied some time after that because of delay. another example: kick goes in, dmg is dealt, spell is not interrupted, I'm not sure I'm experssing myself correctly.

**Comment by Iliana-sc** [comment]
yes, that is indeed how I understood it and that is how it worked on retail from vanilla up to and including mists of pandaria

**Comment by neroz7** [comment]
I don't want to go into big arguments, because you seem to know what you are talking about, however after playing through 8 seasons in WoW from TBC up to wotlk I have never once kicked someone in a school and see that spell still get casted or them not being silenced, I know tbc has a different playstyle from wotlk, I think due to because of having no haste until later on the exp and due to some abilitys sharing gcd (kick for example didn't in wotlk) but still this is something that should be looked into to, if you are casting and you are effected by counterspell / kick w/e, you need to be silenced, I'm just saying this isn't happening in some cases.

**Comment by Iliana-sc** [comment]
you should read through https://www.worldofcorecraft.com/content/spell-delay it links to sources and explains what you see

**Comment by neroz7** [comment]
"\* This means our implementation of spells in the air breaking stealth and vanish, as shown in our rogue video, was incorrect and has now been removed."  Now I'm even more worried, because I know for a fact that icelancing or counterspelling a vanish in a correct timing would cause the rogue to be unvanished ( most instant spells did this ).

**Comment by somnu** [comment]
neroz7 is right, I also felt the same delay, but didn't know how to actually explain it. Also there is the fact that the server is noticeably laggy, I'm from europe and it feels like I'm playing on an US server.

**Comment by Iliana-sc** [comment]
they say their implementation was incorrect and was removed because spell delay handles that now
not that the mechanic is completely removed...

I'm done trying to explain this to you because you obviously refuse to download a pvp video from that time and look at it frame by frame.

**Comment by Piranhaz** [comment]
I don't understand why some ppl that don't know about the spelldelay think it's woking correctly...IT ISN'T the delay seems wrong programmed or some shit, but this is not how it supposed to be! u can argue whatever u want and say i'm wrong but i play this game since classic and i started like 10 warriors and pvped so much, i would knew if this delay is working like intended. i can't even get a harmstring on some ppl coz of laggy delay things

**Comment by jessyo** [comment]
^ this

**Comment by neroz7** [comment]
? The same implementation that was incorrect like they said actually happened alot in retail, like I just mentioned in my previous comment, I have no idea why you are talking to me like that and defending this blindly, I'm telling you that from my experience there is something wrong with the delay on the server, and never, ever in retail did it happen for a kick or counterspell to hit and the target finishing his school without being locked out of it, I've always played pvp for 8 seasons and I'm quite experienced, same for my friends, we intend to start playing here, and it's not just me saying this, we all felt that something fishy was happening, all I ask is that the devs look into it. Illiana, instead of just telling me to go look at a pvp video, maybe you should make a character and experience PvP on CC for yourself? Tell me your experience and maybe then you will understand what I'm talking about.

**Comment by neroz7** [comment]
@piranhaz, that might just be lag, what I'm refering to is if you hit harmstring, but the slow only gets applied abit later, that is what I think is happening atleast.

**Comment by jessyo** [comment]
I think they just fixed it by restarting the server. 

It's much smoother now, turns out it was just server lag and not spell delay.

**Comment by Iliana-sc** [comment]
Have you done the following:
1. Download a pvp video of a warrior that casts hamstring on an enemy (DOWNLOAD not youtube)
2. Find the location where he casts hamstring on a target
3. Look at that frame by frame
4. Confirm that yes, you actually see the delay in application
5. Accept that you are wrong
6. Repeat the above steps for other spells that aren't hamstring

**Comment by neroz7** [comment]
There is no point discussing this with you, you either haven't played played PvP in CC or PvP in retail, maybe both, I know what the delay you are talking about is, and I can say that it isn't working like that in corecraft atm, perhaps it is the result of server lag affecting the delay, but still cases where kick and counterspell don't work on the spellcast should not be explained by this delay.

**Comment by neroz7** [comment]
I will record gameplay footage of next server test to try and get to show you if the issue is fixed or not, I should have done it this time and I feel pretty dumb about not doing it, if any of the devs can look into what I wrote in this topic and see if this is simply server lag + delay affecting gameplay or if there is actually something else wrong.

**Comment by Iliana-sc** [comment]
Whatever you are seeing is not a bug in spell delay. Please stop being dense.

**Comment by neroz7** [comment]
I never said that it would be a spell delay bug, I simply pointed to that possibility, if further investigating this reaches that conclusion, so be it, fact is that kick and counterspell sometimes had that behaviour, and we noticed it on other spells too, you were the one who pointed imediatly towards it being related to spell delay and working has intended.

**Comment by Klimpb** [comment]
During half of the test or so they had some issues causing you to experience a lot of extra lagg which many people seem to think was the implemented "spell delay".

**Comment by Piranhaz** [comment]
The restart they did fixed the delay..and wow illiana, stop arguing pls, it's annoying to read "watch a video and see that u are wrong" when u have no idea what we are talking about.

**Comment by Bugreporta** [comment]
Lliana-sc what are you trying to defend? This is clearly a bug and is in no way retail-like as u describe it. Did u even participate in the test honestly.

As Neroz wrote "I would kick spells, and a small delay would be felt"  this describes the bug well enough, and that was exactly how i felt it playing Warlock with Spell Lock, Rogue with Kick and Mage with Counterspell.

And the fact that we have nothing to back it up, you can do something as simple as compare it with
http://www.youtube.com/watch?v=K4WR0JW5jWM&t=15m50s (Watch the focus frame 15.56)
Notice how the counterspell immediately interrupts the Flash Heal.

The icon is delayed a tiny bit, but the interrupt itself is next to instant as it should be.
This might have been caused by a server delay, i cant say exactly but nothing else seem to have had the same delay.
And yes someone should've recorded it making it easier to spot.

**Comment by neroz7** [comment]
@bugreporta thank you for noticing, it seems like you were the only one who also noticed this happening, which any player who did 10 minutes of arena would've realized, anyone arguing otherwise never even bothered to test this and is just talking shit atm, will record my next test gameplay to see if this still goes on or gets fixed, that video you linked describes exactly how it should be working and I gotta say that on CC this test worked nothing like that sometimes.

**Comment by solowt** [comment]
Hey,

Some delay certaintly existed for poisons and debuffs being applied on retail during TBC.  You can, indeed, notice this in any video from TBC.

However, to me, it felt like there was too much delay in this test and particularly too much delay when it comes to interrupts.

**Comment by Klimpb** [comment]
Go read this:
http://us.battle.net/wow/en/forum/topic/13087818929?page=6#114

**Comment by Lobogo** [comment]
there was an issue with some leak in code (im no programmer so if it doesnt make sense ask shiro on irc) which resulted in much greater delay and/or lag, which was solved with server restart
it had NOTHING to do with the spell delay implementation

**Comment by Barroth** [comment]
^^ what lobogo said,  the leak caused the server's update cycle taking time up to 500ms. That + the normal spell delay made it feel very laggy

**Comment by Schaka** [comment]
Lol 900ms+latency = kicking casts at the start and still not interrupting
That must've been fun

**Comment by ccshiro** [comment]
What @SuddenDeath, @Lobogo and @Barroth said.
