### ISSUE TITLE
Continuing casting while stunned

### ISSUE THREAD

**Issue by ghost** [ccshiro/cc-buglist#1887]
This only occurs with this specific Boulderfist Mage. He's able to cast his frostbolt even when I open with pounce; intended?

![wowscrnshot_100315_004147](https://cloud.githubusercontent.com/assets/13790554/10261953/d450bd38-6967-11e5-90c5-48f04df5a8d3.jpg)

Again, this only occurs with this specific Boulderfist Mage.

**Comment by ccshiro** [comment]
Unable to make this trigger at all. My guess is this was fixed at some point, since the issue is rather old, and mob AI has been changed a bunch since. If it presents itself again, please reopen the issue.

**Comment by Bahalol** [comment]
I lost the account responsible for this report so I cannot re-open it, but the issue is still occurring on the test server. What appears to be happening is, if I am very close to the mob and it detects that I am there but does not engage me in combat and I subsequently open with a stun, it will ignore the logic and continue to cast its move as if I had engaged it normally. This occurs 100% of the time with _this_ specific mob.

![wowscrnshot_062616_134717](https://cloud.githubusercontent.com/assets/17086469/16363942/f853c0b4-3ba7-11e6-9e46-f06d113b8a76.jpg)

Edit: After further testing, this has occurred with all stationary mobs that cast moves.

![wowscrnshot_062616_145803](https://cloud.githubusercontent.com/assets/17086469/16364155/8c470a6e-3bae-11e6-812c-5b071dd9ef16.jpg)

**Comment by Bahalol** [comment]
Steps for reproduction: 
1.) Engage a stationary mob or a mob that's intended to patrol but is stationary (i.e., a bugged patrol).
2.) Allow it to detect you in stealth but do not allow it to engage you in combat.
3.) Open with a stun. The mob should disregard crowd control logic and continue to cast its move despite it being incapacitated.

**Comment by Bahalol** [comment]
> Steps for reproduction: 
 1.) Engage a stationary mob or a mob that's intended to patrol but is stationary (i.e., a bugged patrol).
 2.) Allow it to detect you in stealth but do not allow it to engage you in combat.
 3.) Open with a stun. The mob should disregard crowd control logic and continue to cast its move despite it being incapacitated.

**Comment by Bahalol** [comment]
Observations from further testing: 
If the spell of the incapacitated enemy target is a cast, it will not follow through and simply fizzle out.
If the spell of the incapacitated enemy target is channeled, it will follow through and cause damage even when stunned.
